apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-toolbox
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-toolbox
  template:
    metadata:
      labels:
        app: postgres-toolbox
    spec:
      containers:
        - name: postgres-toolbox
          image: rudester/postgres-toolbox:latest
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
